/**
 * DATA CLIENT — the app's one connection to its data backend.
 *
 * The app does not depend on any particular backend. Every screen imports
 * `db` from this file and calls it in one style: `db.from('orders')
 * .select(...).eq(...)`, `db.auth.signInWithPassword(...)`,
 * `db.channel(...)`, `db.storage.from(...)`. Whatever backend you choose
 * only has to answer those calls. Pick one with VITE_BACKEND_PROVIDER:
 *
 *  - custom — your own backend (Firebase, a REST API, .NET, Node, anything).
 *    Write an adapter in ./customClient.ts that turns the calls above into
 *    requests to your API. ./localClient.ts is a complete working adapter
 *    (it stores everything in the browser) to copy from; the interface is
 *    `DataClient` in ./customClient.ts.
 *  - supabase (the default) — no adapter needed: set VITE_SUPABASE_URL and
 *    VITE_SUPABASE_ANON_KEY and the official Supabase client answers the
 *    calls directly. This is just the shortest path, not a requirement.
 *
 * With no backend configured:
 *  - `npm run dev` / `npm run build:dev` use ./localClient.ts, so the app
 *    runs with nothing connected (sign in with any email and password).
 *  - `npm run build` (a release) shows "Service unavailable" instead of
 *    starting — a money app must never quietly run on a pretend backend —
 *    and the local stand-in is left out of the release bundle entirely.
 *
 * ── What the data backend must provide ─────────────────────────────────────
 *
 * Column names and types for every table below are in ./schema.ts, and
 * every query in the app is type-checked against it. That file is the data
 * contract, whatever the backend: keep it matching what your backend
 * returns (with Supabase it can be regenerated by the Supabase CLI) and run
 * `npm run typecheck` to find any mismatch. Each user must only be able
 * to see and change their own rows.
 *
 *   Table                     The app...
 *   profiles                  reads its own row; creates it at sign-up
 *                             (upsert); updates document paths after upload.
 *                             KYC, CSD and account-status fields must be
 *                             changeable only by the server.
 *   user_roles                reads its own role (BROKER_ADMIN / BROKER_DEALER
 *                             unlock the admin screen)
 *   stocks                    reads the active stock list and prices
 *   stock_price_history       reads today's price ticks for a symbol
 *   ohlcv                     reads daily bars when the trading API is down
 *   orders                    reads its own orders (never writes), newest
 *                             first, joined to stocks(id, symbol, name,
 *                             isin). client_order_id must be the clOrdId the
 *                             trading API returned (Cancel uses it). Status
 *                             values: see OrderStatus in lib/tradingUtils.ts
 *                             (any case; unknown values show as open).
 *   transactions              reads its own wallet transactions. Rows with
 *                             type 'dividend' or 'coupon' (description =
 *                             the security, amount = the payment) fill the
 *                             Dividends screen.
 *   portfolio_snapshots       reads its own daily portfolio values (one row
 *                             per day: snapshot_date, total_value) for the
 *                             performance chart; shown once 7 days exist
 *   watchlist                 reads, adds and removes its own rows
 *   notifications             reads its own; marks them read
 *   notification_preferences  reads and upserts its own row (on user_id)
 *   market_news               reads rows with is_active = true, newest
 *                             published_at first: News shows every
 *                             category, Announcements the company notices.
 *                             The backend adds and retires items; the app
 *                             only reads them.
 *   bonds                     reads one bond by symbol (bond detail only;
 *                             the Bonds page itself shows no data)
 *   market_status             realtime only: an update to the row with
 *                             exchange = 'LuSE' (session_phase,
 *                             trading_allowed) replaces the market status
 *                             from the trading API until its next poll
 *   platform_settings         reads `maintenance_message`; a change to
 *                             `platform_enabled` = 'false' sends users to the
 *                             maintenance screen
 *
 *   Live updates (db.channel(...).on('postgres_changes', { table }))
 *   on: profiles, orders, notifications,
 *   transactions, market_status, platform_settings.
 *   Storage: bucket `kyc-documents`, files under `<user id>/`.
 *   Auth: email + password sign-in and sign-up, password reset by email
 *   (the email link opens <app URL>/reset-password), refresh tokens (used
 *   by biometric sign-in).
 *   Users must be able to sign in straight after sign-up so they can upload
 *   their KYC documents; if email confirmation is on, they upload them
 *   after confirming.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './schema';
import { localClient } from './localClient';
import { createCustomClient } from '@/integrations/data/customClient';
import { IS_PRODUCTION_BUILD } from '@/lib/config';

const provider = ((import.meta.env.VITE_BACKEND_PROVIDER as string | undefined) || 'supabase').trim().toLowerCase();
const url = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const anonKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();

// Supabase only. Sessions live in sessionStorage (never localStorage), so a session ends
// with the app. The one exception is Supabase's one-time PKCE code
// verifiers (keys ending in `code-verifier`): a password-reset or
// email-confirmation link is often opened after the app has been closed,
// and without the verifier that link can't complete. A verifier is useless
// on its own and is deleted as soon as it's used.
const authStorage = typeof window === 'undefined' ? undefined : {
  getItem: (key: string) => (key.endsWith('code-verifier') ? window.localStorage : window.sessionStorage).getItem(key),
  setItem: (key: string, value: string) => (key.endsWith('code-verifier') ? window.localStorage : window.sessionStorage).setItem(key, value),
  removeItem: (key: string) => (key.endsWith('code-verifier') ? window.localStorage : window.sessionStorage).removeItem(key),
};

function createRealClient(): SupabaseClient<Database> | null {
  if (provider === 'custom') {
    // An adapter satisfies the same call surface; the cast is what lets the
    // rest of the app stay unaware of which backend it is talking to.
    return createCustomClient() as SupabaseClient<Database> | null;
  }
  if (url && anonKey && /^https?:\/\//.test(url)) {
    return createClient<Database>(url, anonKey, {
      auth: {
        storage: authStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
      },
    });
  }
  return null;
}

const realClient = createRealClient();

/** True when a real backend (Supabase or a custom adapter) is wired up. */
export const isBackendConfigured = realClient !== null;

export const isProductionMisconfigured = IS_PRODUCTION_BUILD && !isBackendConfigured;

// Used only when no backend is configured. In a production build that is a
// misconfiguration: App.tsx shows "Service unavailable" instead of mounting
// anything that could call this, and any call that slipped through fails
// loudly. The comparison is on import.meta.env.MODE directly so the bundler
// can see the local stand-in is unreachable in production and leave it out
// of the production bundle entirely.
function unconfiguredClient(): SupabaseClient<Database> {
  return new Proxy({}, {
    get() {
      throw new Error('No backend is configured for this build.');
    },
  }) as SupabaseClient<Database>;
}

export const db: SupabaseClient<Database> =
  realClient ??
  (import.meta.env.MODE === 'production'
    ? unconfiguredClient()
    : (localClient as unknown as SupabaseClient<Database>));

export default db;
